# syntax=docker/dockerfile:1.7-labs

## Definite image args
ARG image_registry
ARG image_name=golang
ARG image_version=1.25-astra1.8.x-slim

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                         Base image                          #
#               First stage, prepare environment              #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
FROM ${image_registry}${image_name}:${image_version} AS base-stage

SHELL [ "/bin/bash", "-exo", "pipefail", "-c" ]

ARG \
    user=anonymous \
    uid=100000 \
    gid=65536 \
    version=1.0.0

## Disable CGO by default and try to avoid installing the package: `libc6-compat`
# Source: https://stackoverflow.com/questions/62634820/build-small-image-from-scratch-open-no-such-file-or-directory
# Source: https://www.reddit.com/r/golang/comments/pi97sp/what_is_the_consequence_of_using_cgo_enabled0/
ENV CGO_ENABLED=0

## Install upx and base components
RUN \
    --mount=type=bind,source=./scripts,target=/usr/local/sbin,readonly \
    upx-install.sh \
    && apt-install.sh \
        tzdata \
        zip \
        ca-certificates \
        build-essential \
    && apt-remove.sh

## Create anonymous user
# hadolint ignore=SC2154
RUN \
    mkdir -p \
        /base/etc/ssl/certs \
        /base/sbin \
        /base/usr/src/app \
## UID and GID
    && echo 'root:x:0:' > /base/etc/group \
    && echo "${user}:x:${gid}:" >> /base/etc/group \
    && echo 'root:x:0:0:root:/root:/sbin/nologin' > /base/etc/passwd \
    && echo "${user}:x:${uid}:${gid}:${user}:/nonexistent:/sbin/nologin" >> /base/etc/passwd \
## Nologin binary
    && echo 'int main() { return 1; }' > nologin.c \
    && gcc -Os -no-pie -static -std=gnu99 -s -Wall -Werror -o /base/sbin/nologin nologin.c \
## Copy root cert
    && cp /etc/ssl/certs/ca-certificates.crt /base/etc/ssl/certs/ca-certificates.crt

WORKDIR /usr/share/zoneinfo

## -0 means no compression.  Needed because go's
## tz loader doesn't handle compressed data
RUN zip -q -r -0 /base/zoneinfo.zip .

WORKDIR /opt

## Top-level layer for pumping dependencies
## Necessary, because subsequently the changeable
## layers, which are located below, will change
## and this layer will not be recreated, thereby
## optimizing the build time
COPY scratch/go.* .
RUN go mod download

## The level below, which assumes frequent changes.
## In order to optimize the build time, it is necessary
## to place it below, because the subsequent build
## will analyze the hash checksums, and based on them
## skip the main "long" build, going straight to the
## final part, where the code base will change
## regularly, thereby rebuilding only this layer
## Copy app
COPY scratch/main.go .

## Build app
# hadolint ignore=SC2154
RUN \
    go build \
        -v \
        -ldflags "-extldflags '-static' -w -s -X 'main.AppVersion=${version}'" \
        -installsuffix=static \
        -o curl-uri main.go

## Reduce binary size: ~9.0Mb => ~2.7Mb
RUN \
    echo "Original binary size: $(du -hs curl-uri)" \
    && upx --best --lzma -o curl_uri_compressed curl-uri \
    && echo "Compressed binary size: $(du -hs curl_uri_compressed)"

## Copy optimized app
RUN \
    cp curl_uri_compressed /base/usr/src/app/curl-uri \
    && chmod 755 /base/usr/src/app/curl-uri

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                        Final image                          #
#      Third stage, add only minimal application and deps     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
FROM scratch

## Set base label
LABEL \
    maintainer="Vladislav Avdeev" \
    organization="NGRSoftlab"

## Import the user and group files from the base-stage
COPY --from=base-stage /base/ /

## Use an unprivileged user
USER anonymous:anonymous

## Set timezone data environment
ENV \
    ZONEINFO=/zoneinfo.zip \
    PATH="/usr/src/app" \
    SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

## Run dir
WORKDIR /usr/src/app

## Be gentle and expose port
EXPOSE 8080

ENTRYPOINT [ "curl-uri" ]
